[workspace]
authors = ["axmeu <axmeu079@gmail.com>"]
channels = ["conda-forge"]
name = "DVC-pipeline-for-phoneme-ASR-robustness-to-noise"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"

[pypi-dependencies]
dvc = ">=3.66.1, <4"
datasets = ">=4.6.1, <5"
soundfile = ">=0.13.1, <0.14"
