[workspace]
authors = ["axmeu <axmeu079@gmail.com>"]
channels = ["conda-forge"]
name = "DVC-pipeline-for-phoneme-ASR-robustness-to-noise"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<3.14"
matplotlib = ">=3.10.8,<4"


[pypi-dependencies]
dvc = ">=3.66.1, <4"
datasets = ">=4.6.1, <5"
soundfile = ">=0.13.1, <0.14"
huggingface_hub = ">=0.24.0, <1.0"
transformers = ">=4.47.0, <4.49.0"
torch = ">=2.0.0"
phonemizer = "*"
protobuf = "*"
jiwer = "*"
